# Generated by Django 6.0 on 2025-12-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('job_title', models.CharField(db_index=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, db_index=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('min_years_experience', models.IntegerField(default=0)),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('education_major', models.CharField(blank=True, max_length=100)),
                ('skills', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('raw_text', models.TextField(blank=True)),
                ('pubdate', models.DateTimeField(blank=True, null=True)),
                ('expdate', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-pubdate'],
            },
        ),
    ]
